GET http://localhost:8000/products/ HTTP/1.1
###
POST http://localhost:8000/products/create/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNjI1MTM3LCJpYXQiOjE3NzA2MjQ4MzcsImp0aSI6IjU2NTdjODhlM2I4ZTRlZjlhYzhlMmViNDI5NTRmYWM1IiwidXNlcl9pZCI6IjMifQ.0kMWOlsBiYQkVRywXzubvBxDLLBtQGT1joxNAY8aY8U

{
    "name": "TV",
    "price": 300.00,
    "stock":14,
    "description": "Televission"
}

###
POST http://localhost:8000/products/read_write_delete/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNjI2NDg4LCJpYXQiOjE3NzA2MjYxODgsImp0aSI6IjZlZDZlMzM4OTA4ZDQ1YWZiZjVlZjBmNDFlY2VlMzNlIiwidXNlcl9pZCI6IjMifQ.Hbh4o1R0rxp_jr4oNUQcOzJ37LDEaISfwhCODCS-Ec4

{
    "name": "TV",
    "price": 300.00,
    "stock":14,
    "description": "Televission"
}

###
GET http://localhost:8000/products/read_write_delete/1 HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:8000/products/read_write_delete/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNjI2NDg4LCJpYXQiOjE3NzA2MjYxODgsImp0aSI6IjZlZDZlMzM4OTA4ZDQ1YWZiZjVlZjBmNDFlY2VlMzNlIiwidXNlcl9pZCI6IjMifQ.Hbh4o1R0rxp_jr4oNUQcOzJ37LDEaISfwhCODCS-Ec4

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDcxMTE3NCwiaWF0IjoxNzcwNjI0Nzc0LCJqdGkiOiI5Yzg5YTFhMDA3ZmU0YmEzODFmZmU4ODg4NDI0NTJmZiIsInVzZXJfaWQiOiIzIn0.usdkJg0m1ZQCg0h1OitzJtcAHGm_bmxqYW3WTurSvhA"
}
###
POST http://localhost:8000/order-viewset/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMDA2Nzc5LCJpYXQiOjE3NzE5MjAzNzksImp0aSI6IjU2YzgzZmUzZWU2YjQ0NzdiM2U4NWMwOGFiODY2ZmY2IiwidXNlcl9pZCI6IjEifQ.JNXlAsiaIMUJb8wnLOgtldo9BI1n927OOfaoMLEXtpY

{
    "status": "Confirmed",
    "items":[
        {
            "product":1,
            "quantity":3
        },
        {
            "product":4,
            "quantity":5
        }
    ] 
}
###
PUT http://localhost:8000/order-viewset/7f1fddf9-40ad-4e2e-896e-068d493f81ae/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMDA2Nzc5LCJpYXQiOjE3NzE5MjAzNzksImp0aSI6IjU2YzgzZmUzZWU2YjQ0NzdiM2U4NWMwOGFiODY2ZmY2IiwidXNlcl9pZCI6IjEifQ.JNXlAsiaIMUJb8wnLOgtldo9BI1n927OOfaoMLEXtpY

{ 
    "status": "Confirmed",
    "items":[
        {
            "product":1,
            "quantity":2
        },
        {
            "product":4,
            "quantity":4
        }
    ] 
}


###
GET http://localhost:8000/order-viewset/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMDA2Nzc5LCJpYXQiOjE3NzE5MjAzNzksImp0aSI6IjU2YzgzZmUzZWU2YjQ0NzdiM2U4NWMwOGFiODY2ZmY2IiwidXNlcl9pZCI6IjEifQ.JNXlAsiaIMUJb8wnLOgtldo9BI1n927OOfaoMLEXtpY


###
GET http://localhost:8000/order-viewset/7f1fddf9-40ad-4e2e-896e-068d493f81ae/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMDA2Nzc5LCJpYXQiOjE3NzE5MjAzNzksImp0aSI6IjU2YzgzZmUzZWU2YjQ0NzdiM2U4NWMwOGFiODY2ZmY2IiwidXNlcl9pZCI6IjEifQ.JNXlAsiaIMUJb8wnLOgtldo9BI1n927OOfaoMLEXtpY

###
DELETE http://localhost:8000/order-viewset/7f1fddf9-40ad-4e2e-896e-068d493f81ae/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMDA2Nzc5LCJpYXQiOjE3NzE5MjAzNzksImp0aSI6IjU2YzgzZmUzZWU2YjQ0NzdiM2U4NWMwOGFiODY2ZmY2IiwidXNlcl9pZCI6IjEifQ.JNXlAsiaIMUJb8wnLOgtldo9BI1n927OOfaoMLEXtpY