# Generated by Django 6.0.4 on 2026-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_testimonial_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=12)),
                ('template_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('template_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('template_content', models.TextField(blank=True, null=True)),
                ('template_keyword', models.TextField(blank=True, null=True)),
                ('body_font_style', models.CharField(blank=True, max_length=50, null=True)),
                ('footer_font_style', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
